services:
  scfr.wphpbb.listener:
    class: scfr\wphpbb\event\listener
    arguments:
      - '@template'
      - '@user'
      - '@dbal.conn'
    tags:
      - { name: event.listener }
  scfr.wphpbb.api:
    class: scfr\wphpbb\controller\api
    arguments:
      - '@user'
      - '@dbal.conn'
      - '@controller.helper'

  scfr.wphpbb.permission:
    class: scfr\wphpbb\controller\permission

  scfr.wphpbb.permission:
    class: scfr\wphpbb\controller\permission
