services:
  scfr.wphpbb.crosspatcher:
    class: scfr\wphpbb\controller\CrossPatcher
  scfr.wphpbb.api.helper:
    class: scfr\wphpbb\api\helper
    arguments:
      - @template
      - @user
      - @config
      - @controller.provider
      - @ext.manager
      - @symfony_request
      - @request
      - @filesystem
      - %core.root_path%
      - %core.php_ext%
  scfr.wphpbb.listener:
    class: scfr\wphpbb\event\listener
    arguments:
      - '@template'
      - '@user'
      - '@dbal.conn'
      - '@scfr.wphpbb.wordpress'
    tags:
      - { name: event.listener }
  scfr.wphpbb.api:
    class: scfr\wphpbb\controller\api
    arguments:
      - '@user'
      - '@dbal.conn'
      - '@scfr.wphpbb.api.helper'
      - '@template'

  scfr.wphpbb.permission:
    class: scfr\wphpbb\controller\permission

  scfr.wphpbb.permission:
    class: scfr\wphpbb\controller\permission
  scfr.wphpbb.wordpress:
    class: scfr\wphpbb\controller\Wordpress
    arguments:
      - '@scfr.wphpbb.crosspatcher'
